name: SpotBugs with FindSecBugs

author: GitHub Field Security
description: Run SpotBugs with FindSecBugs, and upload the results to GitHub Code Scanning

inputs:
  spotbugs_version:
    description: 'The version of SpotBugs to use'
    required: false
    default: '4.7.3'
  findsecbugs_version:
    description: 'The version of FindSecBugs to use'
    required: false
    default: '1.12.0'
  spotbugs_target:
    description: 'The target to run SpotBugs against'
    required: false
    default: '*.jar'
  upload_sarif:
    description: 'Whether to upload the SARIF file to GitHub Code Scanning'
    required: false
    type: boolean
    default: 'true'
  java_distribution:
    description: 'The Java distribution to use'
    required: false
    default: 'microsoft'
  java_version:
    description: 'The Java version to use'
    required: false
    default: '11'
  no_cache:
    description: 'Do not use cached versions of the Spotbugs and FindSecBugs tools'
    required: false
    type: boolean
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
    - name: Cache SpotBugs
      if: inputs.no_cache == 'false'
      id: cache-spotbugs
      uses: actions/cache@v3
      with:
        path: /home/runner/work/spotbugs+/spotbugs-${{ inputs.spotbugs_version }}
        key: ${{ runner.os }}-spotbugs-${{ inputs.spotbugs_version }}
    - name: Cache FindSecBugs
      if: inputs.no_cache == 'false'
      id: cache-findsecbugs
      uses: actions/cache@v3
      with:
        path: /home/runner/work/findsecbugs+/findsecbugs-plugin-${{ inputs.findsecbugs_version }}.jar
        key: ${{ runner.os }}-findsecbugs-${{ inputs.findsecbugs_version }}
    - name: Get SpotBugs
      if: inputs.no_cache == 'true' || steps.cache-spotbugs.outputs.cache-hit != 'true'
      env:
        INPUT_SPOTBUGS_VERSION: ${{ inputs.spotbugs_version }}
      run: |
        cd /home/runner/work/
        mkdir -p 'spotbugs+'
        cd 'spotbugs+'
        wget -q https://github.com/spotbugs/spotbugs/releases/download/"${INPUT_SPOTBUGS_VERSION}"/spotbugs-"${INPUT_SPOTBUGS_VERSION}".tgz
        tar -xzf spotbugs-"${INPUT_SPOTBUGS_VERSION}".tgz
        chmod +x spotbugs-"${INPUT_SPOTBUGS_VERSION}"/bin/spotbugs
        echo "Got spotbugs-${INPUT_SPOTBUGS_VERSION}.tgz"
      shell: bash
    - name: Get FindSecBugs
      if: inputs.no_cache == 'true' || steps.cache-findsecbugs.outputs.cache-hit != 'true'
      env:
        INPUT_FINDSECBUGS_VERSION: ${{ inputs.findsecbugs_version }}
      run: |
        cd /home/runner/work/
        mkdir -p 'findsecbugs+'
        cd 'findsecbugs+'
        wget -q https://search.maven.org/remotecontent?filepath=com/h3xstream/findsecbugs/findsecbugs-plugin/"${INPUT_FINDSECBUGS_VERSION}"/findsecbugs-plugin-"${INPUT_FINDSECBUGS_VERSION}".jar
        echo "Got findsecbugs-plugin-${INPUT_FINDSECBUGS_VERSION}.jar"
      shell: bash
    - name: Run SpotBugs
      env:
        INPUT_FINDSECBUGS_VERSION: ${{ inputs.findsecbugs_version }}
        INPUT_SPOTBUGS_TARGET: ${{ inputs.spotbugs_target }}
        SPOTBUGS_HOME: /home/runner/work/spotbugs+/spotbugs-${{ inputs.spotbugs_version }}
        FINDSECBUGS_HOME: /home/runner/work/findsecbugs+/
      run: |
        "${SPOTBUGS_HOME}"/bin/spotbugs -textui -quiet -effort:max -low -bugCategories SECURITY -pluginList "${FINDSECBUGS_HOME}"/findsecbugs-plugin-"${INPUT_FINDSECBUGS_VERSION}".jar -sarif=spotbugs.sarif "${INPUT_SPOTBUGS_TARGET}"
      shell: bash
    - name: Upload SARIF file
      if: inputs.upload_sarif == 'true'
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: spotbugs.sarif
